# Generated by Django 4.2.3 on 2023-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_size_remove_item_size_item_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=120),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
